import './globals.css';

export const metadata = {
  title: '한울메탈릭스',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className='scroll-smooth' lang='ko'>
      <body>{children}</body>
    </html>
  );
}
